# Generated by Django 4.2.7 on 2023-12-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('ref_payment', models.CharField(max_length=100)),
                ('transaction_number', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=100)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=20)),
                ('operator', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_ref', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=100)),
                ('sign_token', models.CharField(max_length=100)),
                ('environement', models.CharField(max_length=20)),
            ],
        ),
    ]
