# Generated by Django 4.2.7 on 2024-01-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Heure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personne_Travaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intia.personnel')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intia.jour')),
            ],
        ),
        migrations.CreateModel(
            name='Jour_Heure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intia.heure')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intia.jour')),
            ],
        ),
        migrations.CreateModel(
            name='Activite_Heure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intia.activite')),
                ('heure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intia.heure')),
            ],
        ),
    ]
