# Generated by Django 4.2.7 on 2024-01-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='desactivation',
            field=models.BooleanField(default=False),
        ),
    ]
