# Generated by Django 4.2.7 on 2024-01-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intia', '0002_personnel_desactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jour_heure',
            name='activite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='intia.activite'),
        ),
    ]
