# Generated by Django 4.1.12 on 2023-11-07 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000000)),
                ('prenom', models.CharField(default=None, max_length=1000000)),
                ('numeros', models.IntegerField()),
                ('email', models.EmailField(max_length=1000000)),
                ('password', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000000)),
                ('montant_actuel', models.IntegerField(default=0)),
                ('objectif', models.CharField(max_length=1000000)),
                ('photos', models.ImageField(upload_to='')),
                ('montant_projet', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme_pixel.type')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000000)),
                ('contenu', models.CharField(max_length=1000000)),
                ('photos', models.ImageField(upload_to='')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme_pixel.type')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_phases', models.CharField(max_length=1000000)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('statut', models.BooleanField(default=False)),
                ('montant', models.BigIntegerField(default=100)),
                ('nom_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme_pixel.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('payment_ref', models.CharField(max_length=1000000)),
                ('montant', models.IntegerField()),
                ('email_personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme_pixel.utilisateur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme_pixel.projet')),
            ],
        ),
    ]
