# Generated by Django 4.1.12 on 2023-11-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0002_utilisateurs_alter_investissement_email_personne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='contenu',
            field=models.TextField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='projet',
            name='objectif',
            field=models.TextField(max_length=1000000),
        ),
    ]
