# Generated by Django 4.1.12 on 2023-11-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0003_alter_produit_contenu_alter_projet_objectif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='contenu',
            new_name='grande_description',
        ),
        migrations.AddField(
            model_name='produit',
            name='petite_description',
            field=models.TextField(default='Nous faisons du bon Elevages'),
        ),
    ]
