# Generated by Django 4.1.12 on 2023-11-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0004_rename_contenu_produit_grande_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='petite_description',
            field=models.CharField(max_length=80),
        ),
    ]
