# Generated by Django 4.1.12 on 2023-11-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0005_alter_produit_petite_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='couverture_principale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='photos',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='photos',
            field=models.ImageField(upload_to='image'),
        ),
    ]
