# Generated by Django 4.2.7 on 2023-12-05 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme_pixel', '0007_utilisateurs_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investissement',
            name='email_personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='username',
            field=models.CharField(max_length=10000),
        ),
    ]
