# Generated by Django 4.2.7 on 2023-12-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0008_alter_investissement_email_personne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investissement',
            name='nombre_part',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
